export type InventoryReportStatus = "live" | "update" | "hold";
export type InventoryReportPriority = "critical" | "high" | "medium";
export type InventoryReportCadence = "Harian" | "Bulanan" | "On demand";

export type InventoryChartDefinition = {
  id: string;
  title: string;
  type: "bar" | "line" | "donut" | "ranking" | "quality" | "route";
  metric: string;
  dimension: string;
  sourceTables: string[];
  insightFocus: string;
};

export type InventoryAvailableFilter = {
  field: string;
  label: string;
  type: "select" | "multiselect" | "boolean";
  options?: string[];
  default?: string;
};

export type InventoryReport = {
  id: string;
  apiReport: string;
  code: string;
  group: string;
  groupTitle: string;
  title: string;
  description: string;
  executiveQuestion: string;
  status: InventoryReportStatus;
  priority: InventoryReportPriority;
  tags: string[];
  sourceTables: string[];
  lastUpdated: string;
  owner: string;
  cadence: InventoryReportCadence;
  dataGrain: string;
  validated: boolean;
  availableFilters?: InventoryAvailableFilter[];
  chartDefinitions: InventoryChartDefinition[];
  qualityNotes: string[];
  readOnly: true;
};

export const inventoryGroups = {
  executive: "Executive Inventory Position",
  master: "Master Data & Quality",
  aging: "Item Aging & Update Quality",
  transaction: "Mutasi & Transaksi",
  purchasing: "Purchasing & Supplier Linkage",
  fertilizer: "Pupuk & Material Estate",
  control: "Kontrol & Audit",
  fuel: "Fuel Inventory",
  vehicle: "Vehicle Running & Workshop",
  hold: "Kandidat Hold",
} as const;

const readOnly = true as const;

export const inventoryReports: InventoryReport[] = [
  {
    id: "stok-gudang",
    apiReport: "stok-gudang",
    code: "INV-01",
    group: "executive",
    groupTitle: inventoryGroups.executive,
    title: "Posisi Stok & Nilai Gudang",
    description: "Executive view nilai persediaan, stok, gudang dominan, top item, dan risiko kualitas master dari IN_ITEM.",
    executiveQuestion: "Berapa nilai inventory saat ini, gudang mana yang paling material, dan item apa yang perlu perhatian?",
    status: "live",
    priority: "critical",
    tags: ["Stok", "Gudang", "Nilai Persediaan", "Executive"],
    sourceTables: ["IN_ITEM", "IN_PRODCAT", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
    lastUpdated: "Mengikuti MAX(IN_ITEM.UpdateDate)",
    owner: "Inventory Control",
    cadence: "Harian",
    dataGrain: "Item per gudang/lokasi",
    validated: true,
    chartDefinitions: [
      {
        id: "stock-value-by-warehouse",
        title: "Nilai Persediaan per Gudang",
        type: "bar",
        metric: "SUM((QtyOnHand + QtyOnHold + QtyOnOrder) * AverageCost)",
        dimension: "LocCode",
        sourceTables: ["IN_ITEM", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
        insightFocus: "Konsentrasi nilai inventory per gudang.",
      },
      {
        id: "stock-value-by-category",
        title: "Komposisi Nilai per Kategori",
        type: "donut",
        metric: "SUM((QtyOnHand + QtyOnHold + QtyOnOrder) * AverageCost)",
        dimension: "ProdCatCode / IN_PRODCAT.Description",
        sourceTables: ["IN_ITEM", "IN_PRODCAT"],
        insightFocus: "Kategori yang paling besar membawa nilai inventory.",
      },
      {
        id: "top-stock-value-items",
        title: "Top Item Berdasarkan Nilai Stok",
        type: "ranking",
        metric: "QuantityClosing * AverageCost",
        dimension: "ItemCode + LocCode",
        sourceTables: ["IN_ITEM"],
        insightFocus: "Item bernilai besar yang perlu diawasi executive.",
      },
      {
        id: "stock-quality-flags",
        title: "Quality Flags Master Stok",
        type: "quality",
        metric: "Count quality flags",
        dimension: "Zero stock, uncategorized, stale, no valid issue",
        sourceTables: ["IN_ITEM"],
        insightFocus: "Risiko kualitas data stok.",
      },
    ],
    qualityNotes: [
      "QuantityClosing = QtyOnHand + QtyOnHold + QtyOnOrder; QuantityClosing = 0 harus ditampilkan sebagai quality/risk flag.",
      "Usage stock issue: ItemType 1 Stock memakai IN_STOCKISSUE/IN_STOCKISSUELN; ItemType 4 Workshop memakai WS_JOBSTOCK.TransType = 1.",
      "MovementCategory memakai jumlah movement stock issue valid: Fast Moving, Moving, Slow Moving, Dead Stock, atau Stale.",
      "ProdCatCode kosong/null/0 harus masuk data-quality note.",
      "LastIssueDate < 2000-01-01 dianggap placeholder.",
    ],
    readOnly,
  },
  {
    id: "asset-stock-valuasi-listing",
    apiReport: "asset-stock-valuasi-listing",
    code: "RPTIN1000011",
    group: "executive",
    groupTitle: inventoryGroups.executive,
    title: "Report Asset Stock Valuasi Listing",
    description: "Listing valuasi stock pabrik seperti Inventory Valuation Listing RPTIN1000011: group by Product Type Code, include Stock dan Workshop item, dan tidak suppress zero balance.",
    executiveQuestion: "Product type dan item mana yang paling material terhadap nilai asset stock pabrik?",
    status: "live",
    priority: "critical",
    tags: ["Asset Stock", "Valuasi", "Inventory Valuation Listing", "RPTIN1000011", "QtyOnHand", "AverageCost", "Workshop"],
    sourceTables: ["IN_ITEM", "IN_MTHENDITEM", "IN_PRODTYPE"],
    lastUpdated: "Current mengikuti IN_ITEM; periode historis mengikuti IN_MTHENDITEM AccYear/AccMonth",
    owner: "Inventory Control",
    cadence: "Harian",
    dataGrain: "Item aktif per Product Type Code dan lokasi untuk ItemType 1 dan 4",
    validated: true,
    availableFilters: [
      { field: "period", label: "Actual Period", type: "select", default: "Bulan berjalan" },
      { field: "accYear", label: "Accounting Year", type: "select" },
      { field: "accMonth", label: "Accounting Month", type: "select", options: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"] },
      { field: "groupBy", label: "Default Group", type: "select", options: ["product_type_code"], default: "product_type_code" },
    ],
    chartDefinitions: [
      {
        id: "valuation-by-product-type",
        title: "Total Amount per Product Type",
        type: "bar",
        metric: "Current: SUM((QtyOnHand + QtyOnHold) * AverageCost); histori: SUM(IN_MTHENDITEM.Amount)",
        dimension: "ProdTypeCode / IN_PRODTYPE.Description",
        sourceTables: ["IN_ITEM", "IN_PRODTYPE"],
        insightFocus: "Product type dengan nilai asset stock paling besar.",
      },
      {
        id: "stock-workshop-active-scope",
        title: "Stock & Workshop Active Scope",
        type: "donut",
        metric: "SUM(QtyOnHand + QtyOnHold)",
        dimension: "ItemType",
        sourceTables: ["IN_ITEM"],
        insightFocus: "Total quantity Stock dan Workshop dihitung dari on hand + on hold.",
      },
      {
        id: "top-valuation-items",
        title: "Top Item by Total Amount",
        type: "ranking",
        metric: "(QtyOnHand + QtyOnHold) * AverageCost",
        dimension: "ItemCode + LocCode",
        sourceTables: ["IN_ITEM"],
        insightFocus: "Item yang paling material terhadap valuasi stock.",
      },
    ],
    qualityNotes: [
      "Source report hasil scan: RPTIN1000011 INVENTORY VALUATION LISTING dari PT. REBINMAS JAYA OIL MILL.",
      "Scope report mengikuti contoh: Include Workshop Item = Yes, Suppress Zero Balance = No, No. of Decimal = 1.",
      "Filter item aktif memakai Status = 1 dan ItemType 1/4 agar jumlah item sama dengan extracted report.",
      "Total quantity = quantity_on_hand + quantity_on_hold.",
      "Current memakai IN_ITEM; periode selain current memakai IN_MTHENDITEM berdasarkan AccYear/AccMonth hasil konversi actual period.",
      "Kolom unit_cost memakai IN_ITEM.AverageCost untuk current; current total_amount = (QtyOnHand + QtyOnHold) x AverageCost; histori memakai IN_MTHENDITEM.AverageCost atau Amount / Qty fallback.",
      "Product type description berasal dari IN_PRODTYPE.Description.",
    ],
    readOnly,
  },
  {
    id: "all-stock-movement-analysis",
    apiReport: "all-stock-movement-analysis",
    code: "INV-ALL-STOCK-MOVEMENT",
    group: "transaction",
    groupTitle: inventoryGroups.transaction,
    title: "ALL Stock Movement Analysis Real Time",
    description: "Analisis movement real-time per item stock/workshop: jumlah stock issue, qty movement, amount movement, tanggal movement terakhir, event terakhir, dan asset amount current sebagai konteks stok.",
    executiveQuestion: "Berapa jumlah/qty/amount movement dari tiap stock, dan item mana yang paling aktif berdasarkan stock issue?",
    status: "live",
    priority: "critical",
    tags: ["All Stock", "Movement Analysis", "Real Time", "Valuation", "Stock Issue", "Fast Moving", "Slow Moving", "Stale", "Dead Stock"],
    sourceTables: ["IN_ITEM", "IN_MTHENDITEM", "IN_PRODTYPE", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
    lastUpdated: "Real-time current stock mengikuti IN_ITEM; histori valuation hanya saat user memilih periode historis memakai IN_MTHENDITEM AccYear/AccMonth",
    owner: "Inventory Control",
    cadence: "Harian",
    dataGrain: "Semua item Stock/Workshop real-time per lokasi dengan asset amount dan movement category",
    validated: true,
    availableFilters: [
      { field: "period", label: "Actual Period", type: "select", default: "Bulan berjalan" },
      { field: "accYear", label: "Accounting Year", type: "select" },
      { field: "accMonth", label: "Accounting Month", type: "select", options: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"] },
      { field: "location", label: "Gudang", type: "multiselect" },
      { field: "category", label: "Kategori / Product Type", type: "multiselect" },
      { field: "groupBy", label: "Default Group", type: "select", options: ["MovementCategory", "Gudang", "product_type_code"], default: "MovementCategory" },
    ],
    chartDefinitions: [
      {
        id: "valuation-by-movement-category",
        title: "Valuation by Movement Category",
        type: "bar",
        metric: "SUM(total_amount), SUM(StockIssueEventCount), SUM(StockIssueQtyAllPeriod)",
        dimension: "MovementCategory",
        sourceTables: ["IN_ITEM", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
        insightFocus: "Kategori movement yang membawa nilai stok dan issue activity terbesar.",
      },
      {
        id: "stock-issue-by-movement-category",
        title: "Stock Issue by Movement Category",
        type: "bar",
        metric: "COUNT issue event, SUM issue qty, SUM issue amount; ItemType 4 dari WS_JOBSTOCK",
        dimension: "MovementCategory",
        sourceTables: ["IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
        insightFocus: "Detail jumlah dokumen stock issue, qty issue, dan amount issue per movement category.",
      },
      {
        id: "top-stock-issue-movement-items",
        title: "Top Stock Issue Movement Items",
        type: "ranking",
        metric: "StockIssueMovementCount, StockIssueMovementQty, StockIssueMovementAmount",
        dimension: "ItemCode + Location",
        sourceTables: ["IN_ITEM", "IN_MTHENDITEM", "IN_STOCKISSUE", "WS_JOBSTOCK"],
        insightFocus: "Item dengan frekuensi dan nilai movement stock issue terbesar.",
      },
    ],
    qualityNotes: [
      "Valuation current memakai (QtyOnHand + QtyOnHold) x AverageCost; periode historis memakai IN_MTHENDITEM.Amount.",
      "MovementCategory dihitung dari StockIssue Movement Count: Fast Moving event >= 6, Moving 2-5, Slow Moving 1, Dead Stock bila stok ada tetapi StockIssue Movement 0, dan Stale bila stok dan movement 0.",
      "StockIssueEventCount, StockIssueQtyAllPeriod, dan StockIssueAmountAllPeriod: ItemType 1 Stock dari IN_STOCKISSUE/IN_STOCKISSUELN; ItemType 4 Workshop dari WS_JOBSTOCK.TransType = 1.",
      "MovementSource wajib ternormalisasi: ItemType 4 = WS_JOBSTOCK, ItemType 1 = STOCK_ISSUE_REGULAR. Mismatch tampil sebagai warning di Quality.",
      "Report ini hanya memuat metrik movement; update-risk tetap di report Stock Aging & Item Movement Health.",
      "Scope item aktif ItemType 1 Stock dan 4 Workshop; ItemType 6 Asset dikeluarkan dari inventory gudang.",
    ],
    readOnly,
  },  {
    id: "item-movement-update-tracking",
    apiReport: "item-stale-update",
    code: "INV-STOCK-AGING",
    group: "master",
    groupTitle: inventoryGroups.master,
    title: "Stock Aging & Item Movement Health",
    description: "Stock Aging Monitor untuk item gudang tipe Stock dan Workshop: item tidak bergerak, dead stock, stok nol, kategori kosong, item tanpa issue valid, dan nilai stok berisiko.",
    executiveQuestion: "Item mana yang harus direview dulu, berapa nilainya, dan gudang mana yang paling berisiko?",
    status: "live",
    priority: "critical",
    tags: ["Item Movement", "Update Tracking", "UpdateDate", "Movement Tracking", "Stale", "Aging", "Update Age", "Master Item", "Audit"],
    sourceTables: ["IN_ITEM", "IN_ITEMCODE", "IN_PRODCAT", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
    lastUpdated: "Mengikuti MAX(IN_ITEM.UpdateDate)",
    owner: "Inventory Control",
    cadence: "Harian",
    dataGrain: "Item aktif tipe Stock/Workshop per gudang/lokasi dengan aging UpdateDate, risk score, issue summary, dan rekomendasi aksi",
    validated: true,
    availableFilters: [
      { field: "updateAgeScope", label: "Update Aging", type: "select", options: ["Update <= 3 Bulan", "Update 3-6 Bulan", "Update 6-12 Bulan", "Tidak Update > 12 Bulan", "Tidak Update > 24 Bulan", "Semua item aktif"], default: "Tidak Update > 12 Bulan" },
      { field: "warehouse", label: "Gudang", type: "multiselect" },
      { field: "category", label: "Kategori", type: "multiselect" },
      { field: "zeroStock", label: "Stok Nol", type: "boolean" },
      { field: "noCategory", label: "Tanpa Kategori", type: "boolean" },
    ],
    chartDefinitions: [
      {
        id: "aging-distribution",
        title: "Distribusi Umur Stok",
        type: "bar",
        metric: "COUNT(*)",
        dimension: "AgingBucket",
        sourceTables: ["IN_ITEM", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
        insightFocus: "Distribusi item aktif, slow moving, stale, dan dead stock.",
      },
      {
        id: "risk-value-by-warehouse",
        title: "Nilai Stok Berisiko per Gudang",
        type: "bar",
        metric: "SUM(NilaiStok stale/dead stock)",
        dimension: "LocCode",
        sourceTables: ["IN_ITEM"],
        insightFocus: "Gudang dengan nilai stok berisiko paling material.",
      },
      {
        id: "top-stale-items-by-value",
        title: "Top Item Stale Berdasarkan Nilai",
        type: "ranking",
        metric: "QuantityClosing * AverageCost",
        dimension: "ItemCode + LocCode",
        sourceTables: ["IN_ITEM"],
        insightFocus: "Item bernilai besar yang tidak bergerak atau tidak update.",
      },
    ],
    qualityNotes: [
      "Scope report hanya ItemType 1 (Stock) dan 4 (Workshop); ItemType 6 (Asset) dikeluarkan karena bukan stok gudang inventory.",
      "Usage stock issue: ItemType 1 Stock memakai IN_STOCKISSUE/IN_STOCKISSUELN; ItemType 4 Workshop memakai WS_JOBSTOCK.TransType = 1.",
      "MovementCategory memakai jumlah movement stock issue valid: Fast Moving, Moving, Slow Moving, Dead Stock, atau Stale.",
      "5.534 item aktif saat validasi tidak punya LastIssueDate valid.",
      "5.269 item aktif saat validasi update lebih dari 12 bulan.",
      "Tanggal 1900 tidak boleh dianggap tanggal transaksi.",
    ],
    readOnly,
  },
  {
    id: "movement-stock",
    apiReport: "mutasi-barang",
    code: "INV-03",
    group: "transaction",
    groupTitle: inventoryGroups.transaction,
    title: "Movement Stock",
    description: "Pergerakan fisik barang — barang masuk, keluar, dan transfer antar gudang berdasarkan transaksi valid. Track movement terakhir dan trend perubahan stok.",
    executiveQuestion: "Apakah movement inventory seimbang, dan bulan mana yang punya nilai transaksi paling material?",
    status: "live",
    priority: "critical",
    tags: ["Movement Stock", "Mutasi", "Masuk", "Keluar", "Transfer", "Trend", "Stock Movement"],
    sourceTables: ["IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK", "IN_STOCKRECEIVE", "IN_STOCKRECEIVELN", "PU_GOODSRCV", "PU_GOODSRCVLN", "IN_STOCKTRANSFER", "IN_STOCKTRANSFERLN"],
    lastUpdated: "Mengikuti tanggal transaksi valid, termasuk PU_GOODSRCV.CreateDate",
    owner: "Inventory Accounting",
    cadence: "Harian",
    dataGrain: "Bulan + jenis mutasi",
    validated: true,
    chartDefinitions: [
      {
        id: "movement-by-month",
        title: "Mutasi Masuk vs Keluar per Bulan",
        type: "line",
        metric: "SUM(Qty), SUM(Amount)",
        dimension: "Bulan transaksi + jenis mutasi",
        sourceTables: ["IN_STOCKISSUE", "WS_JOBSTOCK", "IN_STOCKRECEIVE", "PU_GOODSRCV", "IN_STOCKTRANSFER"],
        insightFocus: "Gap movement masuk, keluar, dan transfer.",
      },
      {
        id: "top-movement-items",
        title: "Top Barang Bergerak",
        type: "ranking",
        metric: "SUM(Amount)",
        dimension: "ItemCode",
        sourceTables: ["IN_STOCKISSUELN", "WS_JOBSTOCK", "IN_STOCKRECEIVELN", "PU_GOODSRCVLN"],
        insightFocus: "Barang dengan movement paling material.",
      },
    ],
    qualityNotes: [
      "ItemType 4 Workshop keluar memakai WS_JOBSTOCK.TransType = 1, bukan IN_STOCKISSUELN.",
      "Goods receipt masuk memakai PU_GOODSRCV.CreateDate dan PU_GOODSRCVLN.StockQty/ReceiveQty.",
      "Tanggal transaksi < 2000-01-01 dikeluarkan dari chart periode.",
      "Tanggal transaksi future dikeluarkan dari movement valid.",
      "Bulan yang tidak muncul tidak otomatis berarti nol operasional.",
    ],
    readOnly,
  },
  {
    id: "monthly-stock-account-movement-details",
    apiReport: "monthly-stock-account-movement-details",
    code: "RPTIN1000015",
    group: "transaction",
    groupTitle: inventoryGroups.transaction,
    title: "MONTHLY STOCK ACCOUNT MOVEMENT DETAILS",
    description: "Report khusus rekonstruksi stock account movement pabrik: opening month-end, issue station/vehicle, ledger, return, goods receive, closing hasil hitung, dan valuasi QtyOnHand + QtyOnHold.",
    executiveQuestion: "Bagaimana opening, movement, dan closing item M untuk DEADS/MEMOV/SLMOV pada periode accounting yang sesuai?",
    status: "live",
    priority: "critical",
    tags: ["RPTIN1000015", "Monthly Stock", "Stock Movement", "Accounting Period", "Pabrik", "PTRJ"],
    sourceTables: ["IN_ITEM", "IN_STOCKANALYSIS", "IN_MTHENDITEM", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK", "WS_JOB", "PU_GOODSRCV", "PU_GOODSRCVLN", "PU_POLN"],
    lastUpdated: "Mengikuti periode aktual yang dikonversi ke AccYear/AccMonth",
    owner: "Inventory Accounting",
    cadence: "Bulanan",
    dataGrain: "Item aktif uppercase M per StockAnalysisCode dan lokasi",
    validated: true,
    availableFilters: [
      { field: "location", label: "Lokasi", type: "select", options: ["PTRJ"], default: "PTRJ" },
      { field: "category", label: "Stock Analysis", type: "select", options: ["DEADS", "MEMOV", "SLMOV"] },
    ],
    chartDefinitions: [
      {
        id: "closing-by-stock-analysis",
        title: "Closing Amount by Stock Analysis",
        type: "bar",
        metric: "SUM(ClosingAmount), SUM((QtyOnHand + QtyOnHold) * AverageCost)",
        dimension: "StockAnalysisCode",
        sourceTables: ["IN_ITEM", "IN_MTHENDITEM", "IN_STOCKISSUE", "WS_JOBSTOCK", "PU_GOODSRCV"],
        insightFocus: "Komposisi nilai closing per DEADS, MEMOV, dan SLMOV.",
      },
      {
        id: "issued-vs-receive",
        title: "Issued vs Goods Receive",
        type: "bar",
        metric: "SUM(IssuedTotalAmount), SUM(GoodsReceiveAmount)",
        dimension: "StockAnalysisCode",
        sourceTables: ["IN_STOCKISSUE", "WS_JOBSTOCK", "PU_GOODSRCV"],
        insightFocus: "Perbandingan nilai keluar dan penerimaan pada periode accounting.",
      },
    ],
    qualityNotes: [
      "Filter period memakai periode aktual YYYY-MM, lalu dikonversi ke AccYear/AccMonth dengan helper accounting-period.",
      "Opening diambil dari IN_MTHENDITEM accounting period sebelumnya; closing dihitung, bukan diambil dari IN_ITEM.",
      "IN_STOCKISSUE/IN_STOCKISSUELN hanya untuk item non-workshop; ItemType 4 Workshop memakai WS_JOBSTOCK.",
      "Valuasi saldo aktif juga ditampilkan dari IN_ITEM: (QtyOnHand + QtyOnHold) x AverageCost.",
      "Base item: LocCode PTRJ, Status aktif, StockAnalysisCode DEADS/MEMOV/SLMOV, ProdTypeCode bukan DC, dan ItemCode uppercase mulai M.",
      "Goods receive amount memakai PU_GOODSRCVLN.StockQty x PU_POLN.Cost.",
    ],
    readOnly,
  },
  {
    id: "pengeluaran-barang",
    apiReport: "pengeluaran-barang",
    code: "INV-04",
    group: "transaction",
    groupTitle: inventoryGroups.transaction,
    title: "Pengeluaran Barang Operasional",
    description: "Audit pemakaian barang ke operasional, cost center, blok, kendaraan, dan status posting.",
    executiveQuestion: "Barang apa yang paling besar keluar ke operasional dan ke cost center mana dibebankan?",
    status: "live",
    priority: "critical",
    tags: ["Pengeluaran", "Issue", "Cost Center", "Operasional"],
    sourceTables: ["IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK", "WS_JOB", "IN_STOCKISSUELN_ACC"],
    lastUpdated: "Mengikuti MAX(IN_STOCKISSUE.PostDate) dan MAX(WS_JOBSTOCK.PostDate/TransDate) untuk workshop",
    owner: "Warehouse Ops",
    cadence: "Harian",
    dataGrain: "Line issue per dokumen",
    validated: true,
    chartDefinitions: [
      {
        id: "top-issued-items",
        title: "Top Barang Keluar by Amount",
        type: "ranking",
        metric: "SUM(Amount)",
        dimension: "ItemCode",
        sourceTables: ["IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
        insightFocus: "Item operasional paling material.",
      },
      {
        id: "issue-by-block",
        title: "Pengeluaran per Block / Account",
        type: "bar",
        metric: "SUM(Amount)",
        dimension: "BlkCode / AccCode",
        sourceTables: ["IN_STOCKISSUELN", "WS_JOBSTOCK", "WS_JOB"],
        insightFocus: "Cost center paling dominan.",
      },
    ],
    qualityNotes: [
      "ItemType 4 Workshop keluar memakai WS_JOBSTOCK.TransType = 1; ItemType 1 Stock tetap memakai IN_STOCKISSUE/IN_STOCKISSUELN.",
      "Blank AccCode/BlkCode/VehCode harus dihitung sebagai quality flag.",
      "PostDate placeholder dikeluarkan dari chart periode.",
    ],
    readOnly,
  },
  {
    id: "goods-receiving-receipt-activity",
    apiReport: "penerimaan-barang",
    code: "INV-05",
    group: "purchasing",
    groupTitle: inventoryGroups.purchasing,
    title: "Goods Receiving & Receipt Activity",
    description: "Goods Receiving & Receipt Activity — Tracking aktivitas penerimaan barang dari supplier dengan referensi PO, item, qty diterima, unit cost, total amount, lokasi, status, dan klasifikasi inventory.",
    executiveQuestion: "Supplier, PO, dan item apa yang paling besar diterima serta berapa nilai pembelian yang masuk ke inventory?",
    status: "live",
    priority: "high",
    tags: ["Goods Receiving", "Receipt Activity", "Goods Receive", "GRN", "Supplier", "PO", "Procurement", "Penerimaan"],
    sourceTables: ["PU_GOODSRCV", "PU_GOODSRCVLN", "PU_POLN", "PU_SUPPLIER", "IN_ITEM", "IN_PRODTYPE"],
    lastUpdated: "Mengikuti MAX(PU_GOODSRCV.CreateDate)",
    owner: "Procurement",
    cadence: "Harian",
    dataGrain: "Line goods receive per supplier dan PO",
    validated: true,
    chartDefinitions: [
      {
        id: "goods-receive-by-supplier",
        title: "Nilai Goods Receive per Supplier",
        type: "bar",
        metric: "SUM(PU_GOODSRCVLN.ReceiveQty * PU_POLN.Cost)",
        dimension: "SupplierCode / SupplierName",
        sourceTables: ["PU_GOODSRCV", "PU_GOODSRCVLN", "PU_POLN", "PU_SUPPLIER"],
        insightFocus: "Supplier dengan nilai penerimaan pembelian terbesar.",
      },
      {
        id: "goods-receive-by-month",
        title: "Nilai Goods Receive per Bulan",
        type: "line",
        metric: "SUM(PU_GOODSRCVLN.ReceiveQty * PU_POLN.Cost)",
        dimension: "CreateDate month",
        sourceTables: ["PU_GOODSRCV", "PU_GOODSRCVLN", "PU_POLN"],
        insightFocus: "Tren barang supplier yang diterima berdasarkan bulan create Good Receipt.",
      },
      {
        id: "top-goods-receive-items",
        title: "Top Item Goods Receive",
        type: "ranking",
        metric: "SUM(PU_GOODSRCVLN.ReceiveQty * PU_POLN.Cost)",
        dimension: "PU_GOODSRCVLN.ItemCode",
        sourceTables: ["PU_GOODSRCVLN", "PU_POLN", "IN_ITEM"],
        insightFocus: "Item penerimaan supplier terbesar.",
      },
    ],
    qualityNotes: [
      "Unit cost diambil dari PU_POLN melalui POLnID. Total amount dihitung dari ReceiveQty x UnitCost agar sesuai nilai GR aktual.",
      "Filter bulan memakai PU_GOODSRCV.CreateDate. GoodsRcvRefDate tetap ditampilkan sebagai tanggal referensi dokumen.",
      "SupplierName fallback ke SupplierCode jika master supplier kosong.",
    ],
    readOnly,
  },
  {
    id: "purchase-request-inventory",
    apiReport: "purchase-request-inventory",
    code: "INV-06",
    group: "purchasing",
    groupTitle: inventoryGroups.purchasing,
    title: "Purchase Request Inventory & Outstanding",
    description: "PR inventory, qty request, received, outstanding, amount, dan item yang belum terpenuhi.",
    executiveQuestion: "PR inventory apa yang masih outstanding dan berpotensi mengganggu supply?",
    status: "live",
    priority: "critical",
    tags: ["PR", "Outstanding", "Purchasing", "Supply"],
    sourceTables: ["IN_PR", "IN_PRLN", "IN_PRLN_ACC"],
    lastUpdated: "Mengikuti MAX(IN_PR.PRDate)",
    owner: "Procurement",
    cadence: "Harian",
    dataGrain: "Line PR per item",
    validated: true,
    chartDefinitions: [
      {
        id: "top-outstanding-pr",
        title: "Top Outstanding Item",
        type: "ranking",
        metric: "SUM(QtyOutstanding)",
        dimension: "ItemCode",
        sourceTables: ["IN_PR", "IN_PRLN"],
        insightFocus: "Item yang belum terpenuhi.",
      },
      {
        id: "pr-status",
        title: "Komposisi Status PR",
        type: "donut",
        metric: "COUNT(PR line)",
        dimension: "Status",
        sourceTables: ["IN_PR", "IN_PRLN"],
        insightFocus: "Status pemenuhan PR.",
      },
    ],
    qualityNotes: ["Amount 0 pada outstanding besar perlu ditandai.", "PRDate placeholder dikeluarkan dari chart."],
    readOnly,
  },
  {
    id: "transfer-antar-gudang",
    apiReport: "transfer-antar-gudang",
    code: "INV-07",
    group: "transaction",
    groupTitle: inventoryGroups.transaction,
    title: "Transfer Antar Gudang",
    description: "Mutasi antar lokasi dari gudang asal ke gudang tujuan, item, qty, dan nilai transfer.",
    executiveQuestion: "Route transfer mana yang paling material dan item apa yang paling sering dipindahkan?",
    status: "live",
    priority: "high",
    tags: ["Transfer", "Gudang", "Movement"],
    sourceTables: ["IN_STOCKTRANSFER", "IN_STOCKTRANSFERLN", "IN_STOCKTRANSFERLN_ACC"],
    lastUpdated: "Mengikuti MAX(IN_STOCKTRANSFER.PostDate)",
    owner: "Warehouse Ops",
    cadence: "Harian",
    dataGrain: "Line transfer per item",
    validated: true,
    chartDefinitions: [
      {
        id: "transfer-route",
        title: "Top Route Transfer",
        type: "route",
        metric: "SUM(Amount)",
        dimension: "LocCode -> ToLocCode",
        sourceTables: ["IN_STOCKTRANSFER", "IN_STOCKTRANSFERLN"],
        insightFocus: "Aliran stok antar gudang.",
      },
      {
        id: "top-transfer-items",
        title: "Top Item Transfer",
        type: "ranking",
        metric: "SUM(Amount)",
        dimension: "ItemCode",
        sourceTables: ["IN_STOCKTRANSFERLN"],
        insightFocus: "Item yang paling banyak dipindahkan.",
      },
    ],
    qualityNotes: ["Lokasi asal/tujuan kosong harus ditandai.", "PostDate placeholder dikeluarkan dari chart."],
    readOnly,
  },
  {
    id: "stock-opname",
    apiReport: "stock-opname",
    code: "INV-08",
    group: "control",
    groupTitle: inventoryGroups.control,
    title: "Stock Opname & Adjustment",
    description: "Audit adjustment stok: qty sebelum/sesudah, selisih qty, dan selisih nilai.",
    executiveQuestion: "Adjustment apa yang paling material dan item mana yang punya selisih terbesar?",
    status: "live",
    priority: "high",
    tags: ["Opname", "Adjustment", "Selisih", "Audit"],
    sourceTables: ["IN_STOCKADJ", "IN_STOCKADJLN", "IN_STOCKADJLN_ACC"],
    lastUpdated: "Mengikuti MAX(IN_STOCKADJ.PostDate)",
    owner: "Internal Control",
    cadence: "On demand",
    dataGrain: "Line adjustment per item",
    validated: true,
    chartDefinitions: [
      {
        id: "adjustment-by-type",
        title: "Selisih Nilai per Tipe Adjustment",
        type: "bar",
        metric: "SUM(D_TotalCost)",
        dimension: "AdjType / TransType",
        sourceTables: ["IN_STOCKADJ", "IN_STOCKADJLN"],
        insightFocus: "Tipe adjustment paling material.",
      },
      {
        id: "top-adjustment-items",
        title: "Top Item Selisih",
        type: "ranking",
        metric: "ABS(D_TotalCost)",
        dimension: "ItemCode",
        sourceTables: ["IN_STOCKADJLN"],
        insightFocus: "Item dengan selisih terbesar.",
      },
    ],
    qualityNotes: ["D_Quantity dan D_TotalCost adalah delta.", "PostDate placeholder dikeluarkan dari chart."],
    readOnly,
  },
  {
    id: "fuel-usage",
    apiReport: "fuel-usage",
    code: "INV-09",
    group: "fuel",
    groupTitle: inventoryGroups.fuel,
    title: "Fuel Usage Inventory",
    description: "Pemakaian BBM sebagai bagian dari inventory: kendaraan, blok, item fuel, qty, dan nilai.",
    executiveQuestion: "Kendaraan/blok mana yang paling besar memakai fuel dan berapa nilainya?",
    status: "live",
    priority: "high",
    tags: ["Fuel", "BBM", "Kendaraan", "Operasional"],
    sourceTables: ["IN_FUELISSUE", "IN_FUELISSUELN", "IN_FUELISSUELN_ACC"],
    lastUpdated: "Mengikuti MAX(IN_FUELISSUE.PostDate)",
    owner: "Estate Operations",
    cadence: "Harian",
    dataGrain: "Line fuel issue per kendaraan/blok",
    validated: true,
    chartDefinitions: [
      {
        id: "fuel-by-vehicle",
        title: "Fuel Usage per Kendaraan",
        type: "ranking",
        metric: "SUM(Amount)",
        dimension: "VehCode",
        sourceTables: ["IN_FUELISSUE", "IN_FUELISSUELN"],
        insightFocus: "Kendaraan dengan pemakaian BBM terbesar.",
      },
      {
        id: "fuel-by-month",
        title: "Trend Fuel Usage",
        type: "line",
        metric: "SUM(Qty), SUM(Amount)",
        dimension: "PostDate month",
        sourceTables: ["IN_FUELISSUE", "IN_FUELISSUELN"],
        insightFocus: "Tren pemakaian BBM per bulan.",
      },
    ],
    qualityNotes: ["VehCode atau BlkCode kosong harus ditandai.", "PostDate placeholder dikeluarkan dari chart."],
    readOnly,
  },
  {
    id: "riwayat-transaksi",
    apiReport: "riwayat-transaksi",
    code: "INV-10",
    group: "control",
    groupTitle: inventoryGroups.control,
    title: "Riwayat Transaksi Inventory",
    description: "Audit trail transaksi inventory dari monthly transaction, lintas DocType, item, account, block, dan vehicle.",
    executiveQuestion: "Tipe transaksi apa yang paling dominan dan apakah histori bulanan konsisten?",
    status: "live",
    priority: "high",
    tags: ["Riwayat", "Audit Trail", "DocType"],
    sourceTables: ["IN_MTHENDTRX"],
    lastUpdated: "Mengikuti MAX(IN_MTHENDTRX.DocDate)",
    owner: "Internal Audit",
    cadence: "Harian",
    dataGrain: "Transaction line",
    validated: true,
    chartDefinitions: [
      {
        id: "trx-by-doctype",
        title: "Transaksi per DocType",
        type: "donut",
        metric: "COUNT(*), SUM(Amount)",
        dimension: "DocType",
        sourceTables: ["IN_MTHENDTRX"],
        insightFocus: "DocType dominan pada histori inventory.",
      },
      {
        id: "trx-by-month",
        title: "Trend Transaksi Bulanan",
        type: "line",
        metric: "SUM(Amount)",
        dimension: "DocDate month",
        sourceTables: ["IN_MTHENDTRX"],
        insightFocus: "Konsistensi histori bulanan.",
      },
    ],
    qualityNotes: ["DocDate placeholder dikeluarkan dari chart.", "Amount nol/negatif perlu dianalisis saat muncul."],
    readOnly,
  },
  {
    id: "return-barang",
    apiReport: "return-barang",
    code: "INV-11",
    group: "control",
    groupTitle: inventoryGroups.control,
    title: "Return Barang",
    description: "Pengembalian barang dari stock issue, termasuk referensi dokumen issue dan nilai return.",
    executiveQuestion: "Return barang apa yang material dan dokumen issue mana yang dikembalikan?",
    status: "live",
    priority: "medium",
    tags: ["Return", "Stock Return", "Audit"],
    sourceTables: ["IN_STOCKRTN", "IN_STOCKRTNLN"],
    lastUpdated: "Mengikuti MAX(IN_STOCKRTN.PostDate)",
    owner: "Warehouse Ops",
    cadence: "Harian",
    dataGrain: "Line return per dokumen",
    validated: true,
    chartDefinitions: [
      {
        id: "return-by-item",
        title: "Top Item Return",
        type: "ranking",
        metric: "SUM(Amount)",
        dimension: "ItemCode",
        sourceTables: ["IN_STOCKRTN", "IN_STOCKRTNLN"],
        insightFocus: "Item return paling material.",
      },
      {
        id: "return-by-month",
        title: "Trend Return",
        type: "line",
        metric: "SUM(Amount)",
        dimension: "PostDate month",
        sourceTables: ["IN_STOCKRTN", "IN_STOCKRTNLN"],
        insightFocus: "Tren pengembalian barang.",
      },
    ],
    qualityNotes: ["Volume data lebih kecil dari issue utama.", "PostDate placeholder dikeluarkan dari chart."],
    readOnly,
  },
  {
    id: "item-stale-update",
    apiReport: "item-stale-update",
    code: "INV-12",
    group: "transaction",
    groupTitle: inventoryGroups.transaction,
    title: "Item Tidak Update & Aging Master",
    description: "Audit IN_ITEM.UpdateDate untuk item gudang tipe Stock dan Workshop: item tidak update lebih dari 1 tahun, nilai stok stale, dan gudang paling terdampak.",
    executiveQuestion: "Item aktif mana yang tidak pernah diperbarui lama tetapi masih membawa nilai stok material?",
    status: "live",
    priority: "critical",
    tags: ["UpdateDate", "Stale", "Aging", "Master Item", "Audit"],
    sourceTables: ["IN_ITEM", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
    lastUpdated: "Mengikuti MAX(IN_ITEM.UpdateDate)",
    owner: "Inventory Control",
    cadence: "Harian",
    dataGrain: "Item aktif tipe Stock/Workshop per gudang dengan aging UpdateDate",
    validated: true,
    chartDefinitions: [
      {
        id: "stale-value-by-warehouse",
        title: "Nilai Item Stale per Gudang",
        type: "bar",
        metric: "SUM(QuantityClosing * AverageCost) untuk UpdateDate > 1 tahun",
        dimension: "LocCode",
        sourceTables: ["IN_ITEM", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
        insightFocus: "Gudang dengan nilai item stale paling material.",
      },
      {
        id: "top-stale-items",
        title: "Top Stale Item by Value",
        type: "ranking",
        metric: "QuantityClosing * AverageCost",
        dimension: "ItemCode + LocCode",
        sourceTables: ["IN_ITEM"],
        insightFocus: "Item lama tidak update yang perlu prioritas audit.",
      },
      {
        id: "update-aging-bucket",
        title: "Bucket Aging UpdateDate",
        type: "quality",
        metric: "COUNT(*)",
        dimension: ">1 tahun, <1 tahun, >2 tahun",
        sourceTables: ["IN_ITEM"],
        insightFocus: "Kualitas freshness master item.",
      },
    ],
    qualityNotes: [
      "UpdateDate adalah metadata master item, bukan tanggal movement transaksi.",
      "Usage stock issue: ItemType 1 Stock memakai IN_STOCKISSUE/IN_STOCKISSUELN; ItemType 4 Workshop memakai WS_JOBSTOCK.TransType = 1.",
      "MovementCategory memakai jumlah movement stock issue valid: Fast Moving, Moving, Slow Moving, Dead Stock, atau Stale.",
      "Scope report hanya ItemType 1 (Stock) dan 4 (Workshop); ItemType 6 (Asset) tidak dihitung sebagai stok gudang.",
      "Filter report mendukung lebih dari 1 tahun, kurang dari 1 tahun, atau semua item aktif.",
      "Saat validasi estate, 5.269 dari 7.483 item aktif tidak update lebih dari 1 tahun.",
    ],
    readOnly,
  },
  {
    id: "purchase-order-history",
    apiReport: "purchase-order-history",
    code: "INV-13",
    group: "purchasing",
    groupTitle: inventoryGroups.purchasing,
    title: "Purchasing Order History per Item & Supplier",
    description: "Histori PO yang menghubungkan barang dengan supplier yang pernah memasok, qty order/receive/invoice, nilai PO, dan tanggal PO terakhir.",
    executiveQuestion: "Supplier mana saja yang memasok item tertentu, dan item mana yang punya konsentrasi pembelian terbesar?",
    status: "live",
    priority: "critical",
    tags: ["PO", "Supplier", "Item Supplier", "Purchasing", "Procurement"],
    sourceTables: ["PU_PO", "PU_POLN", "PU_SUPPLIER", "IN_ITEM"],
    lastUpdated: "Mengikuti MAX(PU_PO.PODate)",
    owner: "Procurement",
    cadence: "Harian",
    dataGrain: "Item + supplier dari line PO",
    validated: true,
    chartDefinitions: [
      {
        id: "top-supplier-po-amount",
        title: "Top Supplier by PO Amount",
        type: "bar",
        metric: "SUM(PU_POLN.Amount)",
        dimension: "SupplierCode / SupplierName",
        sourceTables: ["PU_PO", "PU_POLN", "PU_SUPPLIER"],
        insightFocus: "Supplier dengan konsentrasi nilai PO terbesar.",
      },
      {
        id: "supplier-diversity-by-item",
        title: "Supplier Diversity per Item",
        type: "ranking",
        metric: "COUNT(DISTINCT SupplierCode)",
        dimension: "ItemCode",
        sourceTables: ["PU_PO", "PU_POLN"],
        insightFocus: "Barang yang punya banyak alternatif supplier.",
      },
      {
        id: "po-status-composition",
        title: "Komposisi Status PO",
        type: "donut",
        metric: "COUNT(DISTINCT POID), SUM(Amount)",
        dimension: "PU_PO.Status",
        sourceTables: ["PU_PO", "PU_POLN"],
        insightFocus: "Status pembelian dan exposure nilai PO.",
      },
    ],
    qualityNotes: [
      "Qty outstanding dibaca indikatif dari QtyOrder - QtyReceive pada line PO.",
      "PODate < 2000-01-01 dikeluarkan dari analisis periode.",
      "Saat validasi estate, 7.712 PO valid, 44.379 line, 5.722 item, dan 140 supplier terhubung.",
    ],
    readOnly,
  },
  {
    id: "supplier-purchasing-performance",
    apiReport: "supplier-purchasing-performance",
    code: "INV-14",
    group: "purchasing",
    groupTitle: inventoryGroups.purchasing,
    title: "Supplier Performance & Master Quality",
    description: "Kinerja supplier berdasarkan PO, goods receive, invoice, outstanding invoice, serta kualitas master supplier.",
    executiveQuestion: "Supplier mana yang paling material, dan kualitas master supplier mana yang perlu perhatian audit?",
    status: "live",
    priority: "critical",
    tags: ["Supplier", "PO", "Goods Receive", "Invoice", "Master Quality"],
    sourceTables: ["PU_SUPPLIER", "PU_PO", "PU_POLN", "PU_GOODSRCV", "PU_GOODSRCVLN", "AP_INVOICERCV"],
    lastUpdated: "Mengikuti MAX(PU_PO.PODate) dan PU_SUPPLIER.UpdateDate",
    owner: "Procurement",
    cadence: "Harian",
    dataGrain: "Supplier master dengan agregat PO/GR/invoice",
    validated: true,
    chartDefinitions: [
      {
        id: "supplier-po-ranking",
        title: "Top Supplier by PO Amount",
        type: "ranking",
        metric: "SUM(PU_POLN.Amount)",
        dimension: "SupplierCode",
        sourceTables: ["PU_PO", "PU_POLN", "PU_SUPPLIER"],
        insightFocus: "Supplier paling material secara nilai pembelian.",
      },
      {
        id: "supplier-master-quality",
        title: "Supplier Master Quality Flags",
        type: "quality",
        metric: "COUNT blank Email/Telp/CreditLimit",
        dimension: "PU_SUPPLIER field quality",
        sourceTables: ["PU_SUPPLIER"],
        insightFocus: "Kelengkapan master supplier untuk audit.",
      },
      {
        id: "receive-invoice-coverage",
        title: "Receive vs Invoice Coverage",
        type: "bar",
        metric: "Goods receive amount vs invoice amount",
        dimension: "SupplierCode",
        sourceTables: ["PU_GOODSRCV", "AP_INVOICERCV"],
        insightFocus: "Supplier yang perlu rekonsiliasi PO-GR-invoice.",
      },
    ],
    qualityNotes: [
      "Email, Telp, dan CreditLimit kosong dihitung sebagai quality flag supplier.",
      "Saat validasi estate, 554 dari 591 supplier tidak memiliki email dan 229 tidak memiliki nomor telepon.",
      "Agregasi PO, GR, dan invoice dipisah per supplier agar tidak terjadi double counting join.",
    ],
    readOnly,
  },
  {
    id: "pupuk-stock-procurement",
    apiReport: "pupuk-stock-procurement",
    code: "INV-15",
    group: "fertilizer",
    groupTitle: inventoryGroups.fertilizer,
    title: "Pupuk: Stock, Issue Readiness & Procurement",
    description: "Report khusus kategori pupuk CA2111: stok, nilai, last issue/order, supplier PO terakhir, dan quality flag item pupuk.",
    executiveQuestion: "Pupuk mana yang paling material, supplier mana yang terkait, dan apakah ada pupuk bernilai besar yang stale?",
    status: "live",
    priority: "critical",
    tags: ["Pupuk", "CA2111", "Stock", "PO", "Estate Material"],
    sourceTables: ["IN_ITEM", "PU_PO", "PU_POLN", "PU_SUPPLIER", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
    lastUpdated: "Mengikuti MAX(IN_ITEM.UpdateDate) untuk ProdCatCode CA2111",
    owner: "Estate Operations",
    cadence: "Harian",
    dataGrain: "Item pupuk per gudang dengan last supplier PO",
    validated: true,
    chartDefinitions: [
      {
        id: "fertilizer-stock-value",
        title: "Top Pupuk by Stock Value",
        type: "ranking",
        metric: "QuantityClosing * AverageCost",
        dimension: "ItemCode + LocCode",
        sourceTables: ["IN_ITEM", "IN_STOCKISSUE", "IN_STOCKISSUELN", "WS_JOBSTOCK"],
        insightFocus: "Pupuk dengan nilai stok terbesar.",
      },
      {
        id: "fertilizer-po-supplier",
        title: "PO Pupuk by Supplier",
        type: "bar",
        metric: "SUM(PU_POLN.Amount)",
        dimension: "SupplierCode",
        sourceTables: ["PU_PO", "PU_POLN", "PU_SUPPLIER"],
        insightFocus: "Supplier utama untuk pupuk.",
      },
      {
        id: "fertilizer-stale-quality",
        title: "Pupuk Stale & Last Issue Quality",
        type: "quality",
        metric: "COUNT stale / no valid issue movement",
        dimension: "Item pupuk",
        sourceTables: ["IN_ITEM"],
        insightFocus: "Pupuk yang perlu review karena tidak update atau tidak punya issue valid.",
      },
    ],
    qualityNotes: [
      "Definisi pupuk menggunakan IN_ITEM.ProdCatCode = CA2111.",
      "Usage stock issue: ItemType 1 Stock memakai IN_STOCKISSUE/IN_STOCKISSUELN; ItemType 4 Workshop memakai WS_JOBSTOCK.TransType = 1.",
      "MovementCategory memakai jumlah movement stock issue valid: Fast Moving, Moving, Slow Moving, Dead Stock, atau Stale.",
      "LastIssue tidak valid dihitung dari movement aktual; ItemType 4 memakai WS_JOBSTOCK.",
      "Saat validasi estate, 106 item pupuk aktif, 21 item ada stok, dan nilai stok pupuk sekitar Rp13,43B.",
    ],
    readOnly,
  },
  {
    id: "vehicle-running-workshop",
    apiReport: "vehicle-running-workshop",
    code: "INV-16",
    group: "vehicle",
    groupTitle: inventoryGroups.vehicle,
    title: "Vehicle Running & Workshop Inventory Usage",
    description: "Executive view kendaraan: running/usage unit, pemakaian sparepart workshop, biaya stock workshop, service date, dan linkage ke master kendaraan.",
    executiveQuestion: "Kendaraan mana yang paling besar usage/workshop cost dan membutuhkan perhatian operasional?",
    status: "live",
    priority: "high",
    tags: ["Vehicle", "Running", "Workshop", "Sparepart", "Usage"],
    sourceTables: ["GL_VEHICLE", "BD_VEHICLERUNNING", "GL_VEHUSAGE", "GL_VEHUSAGELN", "WS_JOB", "WS_JOBSTOCK"],
    lastUpdated: "Mengikuti MAX(GL_VEHUSAGELN.TransactDate) dan MAX(WS_JOBSTOCK.PostDate)",
    owner: "Estate Operations",
    cadence: "Harian",
    dataGrain: "Kendaraan dengan agregat usage dan workshop stock",
    validated: true,
    chartDefinitions: [
      {
        id: "vehicle-workshop-cost",
        title: "Top Vehicle by Workshop Stock Amount",
        type: "ranking",
        metric: "SUM(WS_JOBSTOCK.Amount)",
        dimension: "VehCode",
        sourceTables: ["WS_JOB", "WS_JOBSTOCK", "GL_VEHICLE"],
        insightFocus: "Kendaraan dengan pemakaian sparepart/stock workshop terbesar.",
      },
      {
        id: "vehicle-usage-unit",
        title: "Usage Unit Ranking",
        type: "bar",
        metric: "SUM(GL_VEHUSAGELN.UsageUnit)",
        dimension: "VehCode",
        sourceTables: ["GL_VEHUSAGE", "GL_VEHUSAGELN"],
        insightFocus: "Kendaraan dengan running/usage unit tertinggi.",
      },
      {
        id: "workshop-stock-concentration",
        title: "Workshop Stock Item Concentration",
        type: "quality",
        metric: "COUNT(DISTINCT ItemCode), SUM(Amount)",
        dimension: "VehCode",
        sourceTables: ["WS_JOBSTOCK"],
        insightFocus: "Konsentrasi pemakaian item workshop per kendaraan.",
      },
    ],
    qualityNotes: [
      "WS_JOBSTOCK.VehCode banyak kosong, sehingga report menggunakan fallback ke WS_JOB.VehCode.",
      "GL_VEHFUELUSAGE kosong saat validasi, sehingga fuel detail tetap memakai IN_FUELISSUE.",
      "Saat validasi estate, GL_VEHUSAGELN memiliki 248.813 line dan WS_JOBSTOCK 47.409 line.",
    ],
    readOnly,
  },
  {
    id: "expiry-inventory",
    apiReport: "expiry-inventory",
    code: "INV-H01",
    group: "hold",
    groupTitle: inventoryGroups.hold,
    title: "Expiry Date Inventory",
    description: "Kandidat report expiry date inventory. Ditahan karena tabel expiry kosong saat validasi.",
    executiveQuestion: "Belum layak live sampai data expiry tersedia.",
    status: "hold",
    priority: "medium",
    tags: ["Expiry", "Hold"],
    sourceTables: ["IN_ITEMEXPDATE", "IN_STOCKISSUE_EXDATE", "IN_STOCKRECEIVE_EXDATE"],
    lastUpdated: "Tidak tersedia",
    owner: "Inventory Control",
    cadence: "On demand",
    dataGrain: "Expiry line",
    validated: false,
    chartDefinitions: [],
    qualityNotes: ["Tabel sumber kosong saat validasi; jangan tampilkan sebagai report live."],
    readOnly,
  },
];

const pinnedInventoryReportIds = ["penerimaan-barang"];

function reportOrder(report: InventoryReport) {
  const pinnedIndex = pinnedInventoryReportIds.indexOf(report.id);
  return pinnedIndex === -1 ? Number.MAX_SAFE_INTEGER : pinnedIndex;
}

export const liveInventoryReports = inventoryReports
  .filter((report) => report.status !== "hold")
  .sort((a, b) => reportOrder(a) - reportOrder(b));

export const inventoryReportsByGroup = Object.entries(inventoryGroups).map(([group, title]) => ({
  group,
  title,
  reports: inventoryReports
    .filter((report) => report.group === group)
    .sort((a, b) => reportOrder(a) - reportOrder(b)),
}));

const inventoryReportAliases: Record<string, string> = {
  "seluruh-stock-summary": "asset-stock-valuasi-listing",
  "report-asset-stock-valuasi-listing": "asset-stock-valuasi-listing",
};

export const getInventoryReport = (id: string) =>
  inventoryReports.find((report) => {
    const canonicalId = inventoryReportAliases[id] ?? id;
    return report.id === canonicalId || report.apiReport === canonicalId || report.code === id;
  });
