-- Get IN_ITEM schema (50 columns)
SELECT
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.CHARACTER_MAXIMUM_LENGTH,
    c.NUMERIC_PRECISION,
    c.NUMERIC_SCALE,
    c.IS_NULLABLE,
    c.COLUMN_DEFAULT,
    c.ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS c
WHERE c.TABLE_NAME = 'IN_ITEM'
ORDER BY c.ORDINAL_POSITION;

-- Run via SQL Gateway:
-- curl -s -X POST http://localhost:8001/v1/query \
--   -H "Content-Type: application/json" \
--   -H "x-api-key: 2a993486e7a448474de66bfaea4adba7a99784defbcaba420e7f906176b94df6" \
--   -d '{"sql":"SELECT c.COLUMN_NAME, c.DATA_TYPE, c.CHARACTER_MAXIMUM_LENGTH, c.IS_NULLABLE, c.ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = '\''IN_ITEM'\'' ORDER BY c.ORDINAL_POSITION","database":"db_ptrj_mill"}'