import type { ReportPreset } from './types'

export const STOCK_AGING_REPORT_IDS = new Set(['item-movement-update-tracking', 'item-stale-update'])
export const MOVEMENT_ANALYSIS_REPORT_IDS = new Set(['all-stock-movement-analysis'])
export const ASSET_VALUATION_REPORT_IDS = new Set(['asset-stock-valuasi-listing'])
export const MONTHLY_STOCK_MOVEMENT_REPORT_IDS = new Set(['monthly-stock-account-movement-details'])
export const MONTHLY_OFFICIAL_DETAIL_COLUMNS = [
  'ItemCode',
  'ItemDescription',
  'UOM',
  'OpeningQty',
  'OpeningAmount',
  'ReceivedQty',
  'ReceivedAmount',
  'ReturnAdviceQty',
  'ReturnAdviceAmount',
  'TransferredQty',
  'TransferredAmount',
  'AdjustmentQty',
  'AdjustmentAmount',
  'LedgerQty',
  'LedgerAmount',
  'IssuedStationQty',
  'IssuedStationAmount',
  'IssuedVehicleQty',
  'IssuedVehicleAmount',
  'IssuedTotalQty',
  'IssuedTotalAmount',
  'ReturnQty',
  'ReturnAmount',
  'GoodsReceiveQty',
  'GoodsReceiveAmount',
  'GoodsReturnQty',
  'GoodsReturnAmount',
  'DispatchAdvQty',
  'DispatchAdvAmount',
  'ClosingQty',
  'ClosingAmount',
]
export const MONTHLY_CONTEXT_DETAIL_COLUMNS = [
  'MovementCategory',
  'MovementActivityCountActual',
  'MovementActivityQtyActual',
  'MovementActivityAmountActual',
  'MovementIssueCountActual',
  'MovementIssueQtyActual',
  'MovementIssueAmountActual',
  'MovementLastIssueDate',
  'ProductTypeCode',
  'ProductTypeDescription',
  'ProductCategoryCode',
  'ProductBrandCode',
  'ProductModelCode',
  'ProductMaterialCode',
  'ItemType',
  'ItemTypeName',
  'QtyOnHand',
  'QtyOnHold',
  'QtyOnHandHold',
  'OnHandHoldAmount',
  'AverageCost',
]
export const PERIOD_SCOPED_REPORT_IDS = new Set([
  ...STOCK_AGING_REPORT_IDS,
  ...MOVEMENT_ANALYSIS_REPORT_IDS,
  ...ASSET_VALUATION_REPORT_IDS,
  ...MONTHLY_STOCK_MOVEMENT_REPORT_IDS,
  'stok-gudang',
  'stok-workshop',
  'stock-issue-by-vehicle',
  'stock-issue-by-station',
])
export const genericTechnicalColumns = new Set([
  'raw_status',
  'technical_id',
  'source_table',
  'period_data_source',
  'ActualPeriodStart',
])
export const periodContextColumns = [
  'report_id',
  'source_report_title',
  'accounting_period',
  'actual_period',
  'acc_year',
  'acc_month',
  'actual_year',
  'actual_month',
  'period_data_source',
]

export const stockAgingBusinessColumns = [
  'KodeBarang',
  'NamaBarang',
  'QtyOnHandHold',
  'AmountItem',
  'MovementCategory',
  'MovementAnalysis',
  'QuantityClosing',
  'StockIssueEventCount',
  'StockIssueQtyAllPeriod',
  'StockIssueAmountAllPeriod',
  'LastStockIssueDate',
  'MovementEventCountAll',
  'MovementQtyAll',
  'MovementAmountAll',
  'LastMovementDate',
  'MovementGapQty',
  'MovementEvent1',
  'MovementEvent2',
  'StockIssueEvent1',
  'StockIssueEvent2',
  'RiskLevel',
  'AgingBucket',
  'UmurBulan',
  'UmurTahun',
  'RecommendedAction',
  'KodeKategori',
  'Kategori',
  'TotalAmount',
  'LastUpdateDate',
  'IssueSummary',
  'Gudang',
]

export const stockAgingTechnicalColumns = new Set([
  ...periodContextColumns,
  'FlagStokNol',
  'FlagTanpaKategori',
  'FlagTanpaIssueValid',
  'product_type_code',
  'product_type_description',
  'product_category_code',
  'stock_analysis_code',
  'location',
  'item_code',
  'description',
  'uom',
  'quantity_on_hand',
  'quantity_on_hold',
  'quantity_on_order',
  'total_quantity',
  'QtyOnHand',
  'QtyOnHold',
  'unit_cost',
  'total_amount',
  'raw_status',
  'technical_id',
  'source_table',
  'period_data_source',
  'ActualPeriodStart',
])

export const stockAgingKpiPresetByLabel: Record<string, string> = {
  'Update <= 3 Bulan': 'Update <= 3 Bulan',
  'Update 6-12 Bulan': 'Update 6-12 Bulan',
  'Tidak Update > 12 Bulan': 'Tidak Update > 12 Bulan',
  'Tidak Update > 24 Bulan': 'Tidak Update > 24 Bulan',
  'Stok Nol': 'Stok Nol',
  'Tanpa Kategori': 'Tanpa Kategori',
}

export const stockAgingVisibleColumns = [
  'RiskLevel',
  'AgingBucket',
  'UmurTahun',
  'UmurBulan',
  'KodeBarang',
  'NamaBarang',
  'Gudang',
  'KodeKategori',
  'ItemCurrent',
  'AmountCurrent',
  'QuantityClosing',
  'MovementCategory',
  'StaleMovementRelation',
  'StockIssueEventCount',
  'JumlahStockIssue',
  'StockIssueQtyAllPeriod',
  'JumlahQtyStockIssue',
  'StockIssueAmountAllPeriod',
  'JumlahAmountStockIssue',
  'LastStockIssueDate',
  'MovementEventCountAll',
  'JumlahMovement',
  'MovementQtyAll',
  'JumlahQtyMovement',
  'MovementAmountAll',
  'JumlahAmountMovement',
  'LastMovementDate',
  'MovementAgeDays',
  'MovementGapQty',
  'MovementEvent1',
  'MovementEvent2',
  'StockIssueEvent1',
  'StockIssueEvent2',
  'MovementGapQty',
  'LastMovementDate',
  'MovementEventCountAll',
  'MovementQtyAll',
  'MovementAmountAll',
  'MovementEvent1',
  'MovementEvent2',
  'StockIssueQtyAllPeriod',
  'StockIssueAmountAllPeriod',
  'StockIssueEventCount',
  'LastStockIssueDate',
  'StockIssueEvent1',
  'StockIssueEvent2',
  'HargaSatuan',
  'TotalAmount',
  'LastUpdateDate',
  'IssueSummary',
]

export const stockAgingPresets: ReportPreset[] = [
  { label: 'Semua Item', description: 'Reset update aging', filters: { stale: 'semua' } },
  { label: 'Update <= 3 Bulan', description: 'Update terakhir <= 3 bulan', filters: { stale: 'active' } },
  { label: 'Update 3-6 Bulan', description: 'Update terakhir 3-6 bulan', filters: { stale: 'watch' } },
  { label: 'Update 6-12 Bulan', description: 'Update terakhir 6-12 bulan', filters: { stale: 'slow-moving' } },
  { label: 'Tidak Update > 12 Bulan', description: 'Update terakhir > 1 tahun', filters: { stale: 'lebih-1-tahun' } },
  { label: 'Tidak Update > 24 Bulan', description: 'Update terakhir > 2 tahun', filters: { stale: 'dead-stock' } },
  { label: 'Stok Nol', description: 'QuantityClosing = 0', filters: { stale: 'semua', columnFilters: [{ field: 'QuantityClosing', operator: 'equals', value: 0 }] } },
  { label: 'Tanpa Kategori', description: 'Kategori kosong/invalid', filters: { stale: 'semua', columnFilters: [{ field: 'KodeKategori', operator: 'blank' }] } },
  { label: 'Nilai Stok Tinggi', description: 'Prioritas nilai terbesar', filters: { stale: 'semua', sortColumn: 'TotalAmount', sortDirection: 'desc', resultLimit: 100 } },
  { label: 'Perlu Review', description: 'Risk score tertinggi', filters: { stale: 'lebih-1-tahun', sortColumn: 'RiskScore', sortDirection: 'desc', resultLimit: 100 } },
]

export const stockAgingManualFilterColumns = [
  'RiskLevel',
  'AgingBucket',
  'Gudang',
  'KodeKategori',
  'KodeBarang',
  'NamaBarang',
  'UmurTahun',
  'ItemCurrent',
  'AmountCurrent',
  'QuantityClosing',
  'MovementCategory',
  'StaleMovementRelation',
  'StockIssueEventCount',
  'JumlahStockIssue',
  'StockIssueQtyAllPeriod',
  'JumlahQtyStockIssue',
  'StockIssueAmountAllPeriod',
  'JumlahAmountStockIssue',
  'LastStockIssueDate',
  'MovementEventCountAll',
  'JumlahMovement',
  'MovementQtyAll',
  'JumlahQtyMovement',
  'MovementAmountAll',
  'JumlahAmountMovement',
  'LastMovementDate',
  'MovementAgeDays',
  'MovementGapQty',
  'MovementEvent1',
  'MovementEvent2',
  'StockIssueEvent1',
  'StockIssueEvent2',
  'MovementGapQty',
  'LastMovementDate',
  'MovementEventCountAll',
  'MovementQtyAll',
  'MovementAmountAll',
  'MovementEvent1',
  'MovementEvent2',
  'StockIssueQtyAllPeriod',
  'StockIssueAmountAllPeriod',
  'StockIssueEventCount',
  'LastStockIssueDate',
  'StockIssueEvent1',
  'StockIssueEvent2',
  'HargaSatuan',
  'TotalAmount',
  'LastUpdateDate',
  'IssueSummary',
]

export const movementAnalysisBusinessColumns = [
  'KodeBarang',
  'NamaBarang',
  'QtyOnHandHold',
  'AmountItem',
  'MovementCategory',
  'StockIssueMovementCount',
  'StockIssueMovementQty',
  'StockIssueMovementAmount',
  'LastStockIssueMovementDate',
  'StockIssueMovementGapQty',
  'MovementAnalysis',
  'StockIssueMovementEvent1',
  'StockIssueMovementEvent2',
  'KodeKategori',
  'Kategori',
  'ItemTypeName',
  'Satuan',
  'Gudang',
]

export const movementAnalysisTechnicalColumns = new Set([
  ...periodContextColumns,
  'RiskLevel',
  'RiskScore',
  'RecommendedAction',
  'AgingBucket',
  'UmurBulan',
  'UmurTahun',
  'StaleMovementRelation',
  'MovementCategoryWindowRank',
  'MovementSource',
  'MovementSourceValid',
  'StockIssueEventCount',
  'JumlahStockIssue',
  'StockIssueQtyAllPeriod',
  'JumlahQtyStockIssue',
  'StockIssueAmountAllPeriod',
  'JumlahAmountStockIssue',
  'LastStockIssueDate',
  'MovementEventCountAll',
  'JumlahMovement',
  'MovementQtyAll',
  'JumlahQtyMovement',
  'MovementAmountAll',
  'JumlahAmountMovement',
  'LastMovementDate',
  'MovementAgeDays',
  'MovementGapQty',
  'MovementEvent1',
  'MovementEvent2',
  'StockIssueEvent1',
  'StockIssueEvent2',
  'IssueSummary',
  'LastUpdateDate',
  'TerakhirUpdate',
  'HariTidakUpdate',
  'KelompokUpdate',
  'product_type_code',
  'product_type_description',
  'product_category_code',
  'stock_analysis_code',
  'location',
  'item_code',
  'description',
  'uom',
  'quantity_on_hand',
  'quantity_on_hold',
  'quantity_on_order',
  'total_quantity',
  'QtyOnHand',
  'QtyOnHold',
  'AverageCost',
  'QuantityClosing',
  'unit_cost',
  'total_amount',
  'raw_status',
  'technical_id',
  'source_table',
  'period_data_source',
  'ActualPeriodStart',
])
export const assetValuationBusinessColumns = [
  'product_type_code',
  'product_type_description',
  'location',
  'item_code',
  'description',
  'MovementCategory',
  'MovementActivityCountActual',
  'MovementActivityQtyActual',
  'MovementActivityAmountActual',
  'MovementIssueCountActual',
  'MovementIssueQtyActual',
  'MovementIssueAmountActual',
  'MovementLastIssueDate',
  'uom',
  'quantity_on_hand',
  'quantity_on_hold',
  'total_quantity',
  'unit_cost',
  'differential_unit_cost',
  'total_amount',
  'product_category_code',
  'product_brand_code',
  'stock_analysis_code',
]

export const assetValuationTechnicalColumns = new Set([
  ...genericTechnicalColumns,
  ...periodContextColumns,
])

