SELECT TOP (1000) [ID]
      ,[AttnDate]
      ,[WorkHours]
      ,[OTHours]
      ,[IsOnLeave]
      ,[LeaveLength]
      ,[TodayIsRestDay]
      ,[TodayIsHoliday]
      ,[CreateDate]
      ,[CreatedBy]
      ,[LastUpdate]
      ,[UpdatedBy]
      ,[PhysMonth]
      ,[PhysYear]
      ,[IsLeaveCountAsManday]
      ,[LocCode]
  FROM [db_ptrj].[dbo].[PR_EMP_ATTN]
  WHERE [EmpCode] = 'A0749'
