SELECT TOP (1000) [ID]
      ,[MasterID]
      ,[TaskCode]
      ,[TaskRtnVal]
      ,[EmpCode]
      ,[EmpName]
      ,[OT]
      ,[ShiftCode]
      ,[Hours]
      ,[Unit]
      ,[Rate]
      ,[Amount]
      ,[Status]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[UpdatedBy]
      ,[UpdatedDate]
      ,[ImpFlag]
      ,[TrxDate]
      ,[ChargeTo]
      ,[NormalDay]
      ,[TappingType]
  FROM [db_ptrj].[dbo].[PR_TASKREGLN]
