/**
 * lib/reports/mock-data.ts
 * Mock report data per module for the PT Rebinmas Report Center.
 * Replace with real API calls once the backend endpoints are ready.
 */

export type MockReportStatus = 'completed' | 'running' | 'scheduled';

export interface MockReport {
  id: string;
  name: string;
  category: string;
  description: string;
  lastRun: string;
  status: MockReportStatus;
  rows: number;
  owner: string;
}

// ─── Module-specific reports ──────────────────────────────────────────────────

const MODULE_REPORTS: Record<string, MockReport[]> = {
  inventory: [
    {
      id: 'inv-stok-gudang',
      name: 'Laporan Stok per Gudang',
      category: 'Stock Position',
      description: 'Posisi stok terkini per gudang, jumlah item, dan nilai persediaan.',
      lastRun: 'Today 09:00',
      status: 'completed',
      rows: 1_240,
      owner: 'Inventory Control',
    },
    {
      id: 'inv-movement-harian',
      name: 'Movement Harian',
      category: 'Inventory Movement',
      description: 'Penerimaan dan pengeluaran barang per hari dengan running balance.',
      lastRun: 'Today 08:30',
      status: 'completed',
      rows: 8_560,
      owner: 'Logistics',
    },
    {
      id: 'inv-valuasi',
      name: 'Valuasi Persediaan',
      category: 'Valuation & Cost',
      description: 'Nilai persediaan berdasarkan metode rata-rata tertimbang dan FIFO.',
      lastRun: 'Today 08:00',
      status: 'completed',
      rows: 640,
      owner: 'Finance',
    },
    {
      id: 'inv-aging',
      name: 'Aging Analysis',
      category: 'Aging & Expiry',
      description: 'Analisis umur persediaan untuk mendeteksi slow-moving dan dead stock.',
      lastRun: 'Yesterday 17:00',
      status: 'completed',
      rows: 3_200,
      owner: 'Inventory Control',
    },
    {
      id: 'inv-stock-opname',
      name: 'Stock Opname',
      category: 'Stock Take',
      description: 'Daftar selisih hasil stock opname fisik vs sistem per gudang.',
      lastRun: 'May 10, 2026',
      status: 'scheduled',
      rows: 312,
      owner: 'Audit',
    },
  ],

  absensi: [
    {
      id: 'abs-daftar-hadir',
      name: 'Daftar Hadir Harian',
      category: 'Daily Attendance',
      description: 'Rekap kehadiran harian seluruh karyawan, termasuk jam masuk dan pulang.',
      lastRun: 'Today 08:00',
      status: 'completed',
      rows: 2_840,
      owner: 'HRD',
    },
    {
      id: 'abs-rekap-bulanan',
      name: 'Rekap Bulanan',
      category: 'Monthly Summary',
      description: 'Ringkasan kehadiran per bulan per departemen dan total HK realization.',
      lastRun: 'May 16, 2026',
      status: 'completed',
      rows: 4_120,
      owner: 'HRD',
    },
    {
      id: 'abs-cuti-kadaluarsa',
      name: 'Kadaluarsa Cuti',
      category: 'Leave Management',
      description: 'Daftar cuti karyawan yang akan expired dalam 30 hari ke depan.',
      lastRun: 'Today 07:00',
      status: 'running',
      rows: 0,
      owner: 'HRD',
    },
    {
      id: 'abs-lembur',
      name: 'Lembur Karyawan',
      category: 'Overtime',
      description: 'Rekap jam lembur per karyawan dan total biaya lembur per periode.',
      lastRun: 'May 16, 2026',
      status: 'completed',
      rows: 870,
      owner: 'Payroll',
    },
  ],

  payroll: [
    {
      id: 'pay-gaji-bulanan',
      name: 'Gaji Bulanan',
      category: 'Salary',
      description: 'Daftar gaji bersih per karyawan termasuk tunjangan dan potongan.',
      lastRun: 'May 15, 2026',
      status: 'completed',
      rows: 1_540,
      owner: 'Payroll',
    },
    {
      id: 'pay-potongan',
      name: 'Daftar Potongan',
      category: 'Deductions',
      description: 'Rincian semua potongan: pajak, bpjs,骑, kasbon, dan lainnya.',
      lastRun: 'May 15, 2026',
      status: 'completed',
      rows: 4_620,
      owner: 'Finance',
    },
    {
      id: 'pay-transfer',
      name: 'Daftar Transfer Bank',
      category: 'Bank Transfer',
      description: 'Data transfer gaji ke bank untuk proses bulk payment.',
      lastRun: 'May 15, 2026',
      status: 'completed',
      rows: 1_510,
      owner: 'Finance',
    },
    {
      id: 'pay-bpjs',
      name: 'Kartu BPJS',
      category: 'Benefits',
      description: 'Kartu BPJS Kesehatan dan Ketenagakerjaan per karyawan.',
      lastRun: 'Apr 30, 2026',
      status: 'scheduled',
      rows: 1_540,
      owner: 'HRD',
    },
    {
      id: 'pay-rekap-pph',
      name: 'Rekap PPH 21',
      category: 'Tax',
      description: 'Daftar penghasilan bruto dan PPH 21 per karyawan per tahun.',
      lastRun: 'Apr 01, 2026',
      status: 'completed',
      rows: 1_540,
      owner: 'Finance',
    },
  ],

  'daftar-upah': [
    {
      id: 'du-reguler',
      name: 'Daftar Upah Reguler',
      category: 'Wage Register',
      description: 'Daftar upah harian reguler per blok dan nama mandor.',
      lastRun: 'May 16, 2026',
      status: 'completed',
      rows: 6_230,
      owner: 'Estate Payroll',
    },
    {
      id: 'du-hk-summary',
      name: 'HK Summary',
      category: 'Attendance',
      description: 'Ringkasan total Hari Kerja (HK) realization vs target per estate.',
      lastRun: 'May 16, 2026',
      status: 'completed',
      rows: 210,
      owner: 'Estate Payroll',
    },
    {
      id: 'du-borongan',
      name: 'Upah Borongan',
      category: 'Piece Rate',
      description: 'Perhitungan upah borongan panen dan konservasi per blok.',
      lastRun: 'May 16, 2026',
      status: 'completed',
      rows: 3_880,
      owner: 'Estate Payroll',
    },
    {
      id: 'du-rekap-bulanan',
      name: 'Rekap Bulanan Estate',
      category: 'Monthly Summary',
      description: 'Gabungan seluruh daftar upah dalam satu periode bulanan.',
      lastRun: 'May 01, 2026',
      status: 'scheduled',
      rows: 10_450,
      owner: 'Estate Payroll',
    },
  ],

  premi: [
    {
      id: 'premi-lembur',
      name: 'Lembur Harian & Mingguan',
      category: 'Overtime',
      description: 'Daftar jam lembur dan biaya lembur per karyawan per periode.',
      lastRun: 'May 16, 2026',
      status: 'completed',
      rows: 960,
      owner: 'Payroll',
    },
    {
      id: 'premi-produksi',
      name: 'Premi Produktifitas',
      category: 'Incentive',
      description: 'Bonus produksi berdasarkan pencapaian target yield per divisi.',
      lastRun: 'May 16, 2026',
      status: 'completed',
      rows: 480,
      owner: 'Estate Management',
    },
    {
      id: 'premi-libur',
      name: 'Premi Hari Libur',
      category: 'Holiday Premium',
      description: 'Perhitungan premi lembur pada hari libur nasional.',
      lastRun: 'May 05, 2026',
      status: 'completed',
      rows: 320,
      owner: 'Payroll',
    },
    {
      id: 'premi-cuti',
      name: 'Premi Cuti Tahunan',
      category: 'Leave Bonus',
      description: 'Tunjangan cuti tahunan yang dibayarkan saat karyawan take leave.',
      lastRun: 'Apr 30, 2026',
      status: 'scheduled',
      rows: 580,
      owner: 'HRD',
    },
  ],

  produktivitas: [
    {
      id: 'pro-harvest',
      name: 'Produktivitas Panen Harian',
      category: 'Harvest Output',
      description: 'Output panen harian per blok, HK realization, dan kg per HK.',
      lastRun: 'Today 07:00',
      status: 'completed',
      rows: 2_160,
      owner: 'Estate Management',
    },
    {
      id: 'pro-manhour',
      name: 'Efisiensi Man Hour',
      category: 'Man Hour',
      description: 'Rasio produktivitas: kg hasil per jam kerja per divisi.',
      lastRun: 'Yesterday 18:00',
      status: 'completed',
      rows: 840,
      owner: 'Estate Management',
    },
    {
      id: 'pro-kpi',
      name: 'KPI Dashboard',
      category: 'KPI',
      description: 'Dashboard KPI utama meliputi yield, efficiency, dan cost per kg.',
      lastRun: 'Today 06:30',
      status: 'running',
      rows: 0,
      owner: 'Management',
    },
    {
      id: 'pro-abc',
      name: 'ABC Analysis Produksi',
      category: 'Analytics',
      description: 'Analisis ABC产出 based on volume contribution per category.',
      lastRun: 'May 15, 2026',
      status: 'completed',
      rows: 1_280,
      owner: 'Analytics',
    },
  ],

  karyawan: [
    {
      id: 'kar-master',
      name: 'Master Data Karyawan',
      category: 'Employee Master',
      description: 'Data master seluruh karyawan termasuk status, jabatan, dan lokasi.',
      lastRun: 'Today 08:00',
      status: 'completed',
      rows: 1_540,
      owner: 'HRD',
    },
    {
      id: 'kar-kontrak',
      name: 'Status Kontrak',
      category: 'Contract Status',
      description: 'Daftar karyawan dengan status kontrak dan tanggal berakhirnya.',
      lastRun: 'Today 07:00',
      status: 'completed',
      rows: 890,
      owner: 'HRD',
    },
    {
      id: 'kar-training',
      name: 'Riwayat Pelatihan',
      category: 'Training',
      description: 'Riwayat pelatihan dan sertifikasi karyawan per periode.',
      lastRun: 'May 10, 2026',
      status: 'completed',
      rows: 3_200,
      owner: 'HC',
    },
    {
      id: 'kar-resign',
      name: 'Karyawan Keluar',
      category: 'Turnover',
      description: 'Daftar karyawan yang resign atau kontraknya tidak diperpanjang.',
      lastRun: 'Apr 30, 2026',
      status: 'completed',
      rows: 45,
      owner: 'HRD',
    },
    {
      id: 'kar-sdm',
      name: 'Laporan SDM Bulanan',
      category: 'HR Report',
      description: 'Rekap seluruh aktivitas SDM bulan berjalan: masuk, keluar, mutasi.',
      lastRun: 'May 01, 2026',
      status: 'scheduled',
      rows: 2_100,
      owner: 'HC',
    },
  ],

  estate: [
    {
      id: 'est-produksi',
      name: 'Produksi Estate Harian',
      category: 'Daily Production',
      description: 'Data produksi harian per blok meliputi berat, quality, dan HK realization.',
      lastRun: 'Today 07:00',
      status: 'completed',
      rows: 1_850,
      owner: 'Estate Management',
    },
    {
      id: 'est-block',
      name: 'Block Yield Report',
      category: 'Block Analysis',
      description: 'Ringkasan yield per blok dan per estate untuk evaluasi produktivitas.',
      lastRun: 'Yesterday 18:00',
      status: 'completed',
      rows: 420,
      owner: 'Estate Management',
    },
    {
      id: 'est-harvest-sched',
      name: 'Jadwal Panen',
      category: 'Harvest Schedule',
      description: 'Jadwal panen blok untuk 14 hari ke depan berdasarkan ripeness survey.',
      lastRun: 'May 16, 2026',
      status: 'completed',
      rows: 310,
      owner: 'Estate Operations',
    },
    {
      id: 'est-cost',
      name: 'Cost per KG',
      category: 'Cost Analysis',
      description: 'Analisis biaya produksi per kilogram per divisi dan per bulan.',
      lastRun: 'Apr 30, 2026',
      status: 'completed',
      rows: 180,
      owner: 'Finance Estate',
    },
  ],

  integrasi: [
    {
      id: 'int-audit',
      name: 'Audit Trail',
      category: 'Audit',
      description: 'Log seluruh perubahan data lintas modul dengan timestamp dan user.',
      lastRun: 'Today 08:00',
      status: 'completed',
      rows: 12_400,
      owner: 'IT Audit',
    },
    {
      id: 'int-sync',
      name: 'Sync Status',
      category: 'Integration',
      description: 'Status sinkronisasi data antar sistem: SP, Gudang, dan Payroll.',
      lastRun: 'Today 07:00',
      status: 'running',
      rows: 0,
      owner: 'IT',
    },
    {
      id: 'int-error',
      name: 'Integration Errors',
      category: 'Error Log',
      description: 'Daftar transaksi gagal sinkron dan action plan penanganannya.',
      lastRun: 'Today 08:30',
      status: 'completed',
      rows: 87,
      owner: 'IT',
    },
    {
      id: 'int-health',
      name: 'System Health Log',
      category: 'Health Check',
      description: 'Status kesehatan seluruh service dan endpoint API integrasi.',
      lastRun: 'Today 08:00',
      status: 'completed',
      rows: 240,
      owner: 'IT Operations',
    },
    {
      id: 'int-data-quality',
      name: 'Data Quality Score',
      category: 'Data Quality',
      description: 'Skor kualitas data per modul berdasarkan completeness dan accuracy.',
      lastRun: 'Yesterday 22:00',
      status: 'completed',
      rows: 18,
      owner: 'IT Audit',
    },
  ],
};

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Returns the mock reports for a given module id.
 * Falls back to an empty array for unknown modules.
 */
export function getMockReportsByModule(moduleId: string): MockReport[] {
  return MODULE_REPORTS[moduleId] ?? [];
}
